substitutions:
  device_name: "athom-cb02-switch"
  friendly_name: "Athom CB02 Switch"
  project_name: "athom.cb02-switch"
  project_version: "1.0"

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true
  platform: ESP8266
  board: esp8285
  project:
    name: "${project_name}"
    version: "${project_version}"

api:

ota:

logger:

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  - platform: gpio
    pin:
      number: 3
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay
      - timing:
          - ON for at least 4s
        then:
          - switch.turn_on: restart_switch

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime Sensor"



switch:
  - platform: restart
    id: restart_switch
    name: "${friendly_name} Restart"

  - platform: gpio
    name: "${friendly_name}"
    pin: GPIO13
    id: relay
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - light.turn_on: blue_led

    on_turn_off:
      - light.turn_off: blue_led

light:
  - platform: status_led
    name: "${friendly_name} Status LED"
    id: blue_led
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO4

time:
  - platform: sntp

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true
